### PR TITLE
explicitly identify Element for PostgresQueue.AsyncIterator

### PR DESCRIPTION
**Pull request by heckj**
This resolves a compilation issue with Swift6 - a possible regression in the compiler provided by Xcode 16 beta 2 (`swift-driver version: 1.110 Apple Swift version 6.0 (swiftlang-6.0.0.4.52 clang-1600.0.21.1.3)`)

While this compiles fine with Swift 5.10, it appears to fail to infer `Element` for `PostgresQueue.AsyncIterator`. The follow error is what I received using `swift build` with the verson of Swift included in the Xcode 16 beta 2 toolchain:

```
/Users/heckj/src/hummingbird-postgres/Sources/HummingbirdJobsPostgres/PostgresJobsQueue.swift:45:20: error: type 'PostgresQueue' does not conform to protocol 'AsyncSequence'
 43 | /// }
 44 | /// ```
 45 | public final class PostgresQueue: JobQueueDriver {
    |                    `- error: type 'PostgresQueue' does not conform to protocol 'AsyncSequence'
 46 |     public typealias JobID = UUID
 47 |

_Concurrency.AsyncSequence:4:20: note: protocol requires nested type 'Element'; add nested type 'Element' for conformance
2 | public protocol AsyncSequence<Element, Failure> {
3 |     associatedtype AsyncIterator : AsyncIteratorProtocol
4 |     associatedtype Element where Self.Element == Self.AsyncIterator.Element
  |                    `- note: protocol requires nested type 'Element'; add nested type 'Element' for conformance
5 |     @available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
6 |     associatedtype Failure = Self.AsyncIterator.Failure where Self.Failure == Self.AsyncIterator.Failure
  |                    `- note: protocol requires nested type 'Failure'; add nested type 'Failure' for conformance
7 |     __consuming func makeAsyncIterator() -> Self.AsyncIterator
8 | }
```

This adds an explicit type for AsyncIterator Element, which resolves the compilation issue.

### CODE REVIEW

**Review by adam-fowler — APPROVED** [review]
looks good

**Comment by adam-fowler** [comment]
Damn CI is reporting another error, can you rebase main

**Comment by adam-fowler** [comment]
@heckj You need to run swiftformat on the code

**Comment by heckj** [comment]
When I ran swiftformat, it cleared up the error in the validation, but also made a change in one of the tests that I explicitly backed up (internal init -> init). I did a broad sweep with `swiftformat .` at the root of the project, `0.54.0` installed. Not earth shattering, but wanted to let you know.

**Comment by adam-fowler** [comment]
@heckj cheers
